source/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('',include('photocontest.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/photocontest/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


from . import views
app_name = 'photocontest'
urlpatterns = [
    #Api for Datatable Creation View
    path('contest_list', views.ContestList.as_view(), name='contest_list'),
    path('likeapi/', views.LikeApi.as_view(), name='like'),
    #Template for Upcoming Contests View
    path('contest_template/', views.ContestTemplate.as_view(), name='contest_template'),
    #Participate in contest View
    path('contest_template/<int:pk>/participate/',views.Participate.as_view() ,name="participate"),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/photocontest/models.py
from django.db import models
from django.contrib.auth.models import User
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
# Create your models here.


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Contest(BaseModel):
    contest_name = models.CharField(max_length=20)
    contest_lastdate=models.DateTimeField(null=True,blank=True)


class Participants(BaseModel):
    participant_user = models.ForeignKey(User, on_delete=models.CASCADE)
    participant_contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    photo = models.ImageField(default='image-not-found.png')
    photo_thumbnail = ImageSpecField(source='photo',
                                        processors=[ResizeToFill(150, 100)],
                                        format='PNG',
                                        options={'quality': 60})


class Likes(BaseModel):
    participant_id = models.ForeignKey(Participants, on_delete=models.CASCADE)
    participant_contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    participant_user = models.ManyToManyField(User)



class Winner(BaseModel):
    winner_name = models.ForeignKey(User, on_delete=models.CASCADE)

source/photocontest/forms.py
from .models import Participants,Winner,Contest
from django import forms
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin

class ParticipantForm(PopRequestMixin, CreateUpdateAjaxMixin,forms.ModelForm):
    photo = forms.FileField(required=False,widget=forms.ClearableFileInput(attrs={'class': 'form-input-styled','accept': 'image/*', 'placeholder': 'Avtar'}))
    class Meta:
        model = Participants
        fields = ['photo']



#     #Validations on each field in form
#
#     def clean_phone1(self):
#         form_data = self.cleaned_data['phone1']
#         if form_data:
#             if len(str(form_data))  < 10 :
#                 raise ValidationError("Enter 10 digits")
#         return form_data
#
#     def clean_phone2(self):
#         form_data = self.cleaned_data['phone2']
#         if form_data:
#             if len(str(form_data))  < 10 :
#                 raise ValidationError("Phone 1 Enter atleast 10 digits")
#         return form_data
#
#
#     def clean_tower_no(self):
#         form_data = self.cleaned_data['tower_no']
#         if form_data:
#             if len(str(form_data))  > 2 :
#                 raise ValidationError("Tower Number cannot be greater than 2 digits")
#         return form_data
#
#     # def clean_v_model(self):
#     #     form_data = self.cleaned_data['v_model']
#     #     if form_data:
#     #         if len(str(form_data)) > 2:
#     #             raise ValidationError("V Model Error ")
#     #     return form_data
#
#
# # class VehicalInformationForm(forms.ModelForm):
# #     model = VehicalInformation
# #     fields = "__all__"
#
# class VehicalUserFormSet(BaseInlineFormSet):
#     # def get_form_kwargs(self, index):
#     #     kwargs = super(VehicalUserFormSet, self).get_form_kwargs(index)
#     #     kwargs.update({'parent': self.instance})
#     #     return kwargs
#
#     def clean(self):
#         super(VehicalUserFormSet, self).clean()
#         if any(self.errors):
#             return
#
#         phone_numbers = []
#         for form in self.form:
#             if len(form.cleaned_data.get('v_model')) > 2:
#                 raise forms.ValidationError(
#                     'V model Error ')
#
#
# VehicalUserFormSet = inlineformset_factory(VehicalUser, VehicalInformation,fields =('plate_no','v_model','v_color','v_type','v_description'),
# widgets={'plate_no': forms.TextInput(attrs={'pattern':'[a-zA-Z0-9]+','class': 'form-control','required':'true','placeholder':'MP23LA0101',"maxlength":"11", 'minlength':"7",'style':"text-transform:uppercase"}),
#          "v_model":forms.TextInput(attrs={'class': 'form-control','maxlength':'20','placeholder':'maruti'}),
#          "v_type":forms.Select(attrs={'class': 'form-control','required':'false','maxlength':'20'}),
#          "v_description":forms.TextInput(attrs={'class': 'form-control','maxlength':'50','placeholder':'This car was stolen'}),
#          "v_color":forms.TextInput(attrs={'class': 'form-control','maxlength':'20','placeholder':'Black'})},
#                                            can_delete=False,extra=1 )
#
#
#
#
#
# DELETED_TYPES = (
#         ('True', 'Inactive'),
#         ('False', 'Active'),
#
#     )
#
# from django.utils.translation import ugettext_lazy as _
#
# class VehicalInformationForm(PopRequestMixin, CreateUpdateAjaxMixin,forms.ModelForm):
#     # deleted = forms.ChoiceField(required=True, choices=DELETED_TYPES,
#     #                                 widget=forms.Select(attrs={'class': 'form-control'}))
#     class Meta:
#         model = VehicalInformation
#         fields = ['plate_no', 'v_model', 'v_color', 'v_type', 'v_description']
#         labels = {
#             'plate_no': _('Plate Number'),
#             'v_model': _('Vehicle Model'),
#             'v_color': _('Vehicle Color'),
#             'v_type': _('Vehicle Type'),
#             'v_description': _('Vehicle Description'),
#
#         }
#         widgets = {'plate_no': forms.TextInput(
#             attrs={'class': 'form-control', 'required': 'true', 'placeholder': 'MP23LA0101', "maxlength": "11"}),
#                    "v_model": forms.TextInput(
#                        attrs={'class': 'form-control', 'maxlength': '20', 'placeholder': 'maruti'}),
#                    "v_type": forms.Select(attrs={'class': 'form-control', 'required': 'false', 'maxlength': '20'}),
#                    "v_description": forms.TextInput(
#                        attrs={'class': 'form-control', 'maxlength': '50', 'placeholder': 'This car was stolen'}),
#                    "v_color": forms.TextInput(
#                        attrs={'class': 'form-control', 'maxlength': '20', 'placeholder': 'Black'})}

source/photocontest/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from braces.views import GroupRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Contest ,Participants ,Likes,Winner
from django_datatables_view.base_datatable_view import BaseDatatableView
from .serializers import ContestSerializer,ParticipantsSerializer,WinnerSerializer
from datetime import datetime
from django.views import generic
from .forms import ParticipantForm
from django.urls import reverse_lazy
from bootstrap_modal_forms.mixins import PassRequestMixin, DeleteMessageMixin
from django.urls import reverse
from rest_framework import generics
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.http import HttpResponse
from rest_framework.views import APIView
from django.contrib.auth.models import User
from django.db.models import Q
import json
class ContestTemplate(generic.TemplateView):
    template_name = "photocontest/contest_list.html"

class ContestList(BaseDatatableView):
    model = Contest
    serializer_class= ContestSerializer

    #Columns to be displayed in datatable
    columns = ['contest_name','contest_lastdate','action']
    order_columns = ['contest_name','contest_lastdate']

    def get_initial_queryset(self):
        #This query ( Select 8 from Contest order-by created_at DESC;)
        qs=Contest.objects.filter(contest_lastdate__gt=datetime.now()).order_by("-created_at")
        return qs

    # This function is used to manually change the columns
    def render_column(self, row, column):
        # We want to render filename as a custom column
        if column == 'contest_name':
            return (row.contest_name).upper()
        elif column == 'contest_lastdate':
            return '%s' % row.contest_lastdate.isoformat()# .strftime('%Y-%m-%d %H:%M:%S')
        elif column == 'action':
            return '<a href="#" class="participate"  data-id="' + str(row.id) + '/participate/"><i class="icon-pencil"></i>Participate</a>'
        else:
            return super(ContestList, self).render_column(row, column)


    def filter_queryset(self, qs):
        # print("Query Set",qs)
        search = self.request.GET.get(u'search[value]', None)
        print("Search", search)
        if search:
            qs = qs.filter(Q(contest_name__icontains=search))
            print("Query Set filter 0", qs)
        return qs

class LikeApi(APIView):

    def post(self,request):
        userid = request.POST.get('userid')
        contestid = request.POST.get('contestid')
        participatedid = request.POST.get('participatedid')
        print("Userid",userid)
        userobject = User.objects.filter(id=userid)[0]
        print("contestid",contestid)
        contestobject = Contest.objects.filter(id=contestid)[0]
        print("participatedid",participatedid)
        participateobject = Participants.objects.filter(id=participatedid)[0]

        if Likes.objects.filter(participant_id_id=participatedid, participant_contest_id=contestid,participant_user__in=userid).exists():
            message = "Your have already Voted for {0} {1}".format(participateobject.participant_user.first_name,participateobject.participant_user.last_name)
            return HttpResponse(json.dumps({"status": "failed", "message": message}), content_type="application/json")
        else:
            if Likes.objects.filter(participant_id_id=participatedid,participant_contest_id=contestid).exists():
                print("Exists")
                likes = Likes.objects.filter(participant_id_id=participatedid,participant_contest_id=contestid)[0]
                likes.participant_user.add(userobject)
            else:
                print("Does Not Exists")
                obj = Likes.objects.create(participant_id=participateobject,participant_contest=contestobject)
                obj.participant_user.add(userobject)
            message = "Your Vote is Submitted for {0} {1}".format(participateobject.participant_user.first_name,participateobject.participant_user.last_name)
            return HttpResponse(json.dumps({"status":"success","message":message}), content_type="application/json")

class Participate(LoginRequiredMixin,PassRequestMixin, SuccessMessageMixin,generic.CreateView):
    model = Participants
    form_class = ParticipantForm
    template_name = "photocontest/participate.html"
    success_message = 'You have successfully participated in this Contest'
    success_url = reverse_lazy('photocontest:contest_template')

    def form_valid(self, form):
        print("valid")
        user_object = self.request.user
        contest_object = Contest.objects.filter(id__iexact=self.kwargs["pk"])[0]
        print("contest_object",contest_object)
        already_exists = Participants.objects.filter(participant_user=user_object,participant_contest=contest_object)
        print("Already Exists")
        if(len(already_exists)>0):
            messages.error(self.request, f'You have already participated earlier in the contest '+str(contest_object.contest_name))
        else:
            self.model = Participants()
            self.model.participant_user = user_object
            self.model.participant_contest = contest_object
            self.model.photo = self.request.FILES['photo']
            self.model.save()
            print("Participate Model Saved")
            messages.success(self.request, f'You have successfully participated in the contest '+str(contest_object.contest_name))
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        print("invalid")
        print("Participate User Errors", form.errors)
        """
        Called if a form is invalid. Re-renders the context data with the
        data-filled forms and errors.

        Args:
            form: Assignment Form
            vehical_information_form: Assignment Question Form
        """
        return self.render_to_response(
            self.get_context_data(form=form,)
        )

    def get_success_url(self):
        return reverse('photocontest:contest_template')

source/content/templates/photocontest/contest_list.html
{% extends 'layouts/default/page.html' %}
{% load static %}
{% load i18n %}
{% block theme-css %}
	<!--This is limitless datatable-->
	<script src="{% static 'global_assets/js/plugins/tables/datatables/datatables.min.js' %}"></script>
	<!--Datepicker Imports-->

	<script src="{% static 'global_assets/js/demo_pages/datatables_extension_colvis.js' %}"></script>

    <!--Django-Modal-form-->
        <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
        <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
    <!--/Django-Modal-Forms-->


{% endblock %}
{% block content %}

<script>


	var offset = new Date().getTimezoneOffset();
	offset = -offset;
        $( document ).ready(function() {


            var loadstatus = LoadData();
            if (loadstatus){
                $('#contestlist').on('mouseover', '.participate', function(){
							$(this).modalForm({formURL: $(this).data('id')}) });
                }
		});

        function LoadData()
        {
			var table= $('#contestlist').DataTable( {
							lengthMenu: [ [10,25,50,100,-1], [10,25,50,100,"All"] ],
							"bJQueryUI": true,
                             "buttons": {
                                    dom: {
                                        button: {
                                            className: 'btn btn-light'
                                        }
                                    },
                             },

							buttons:[ { extend: 'colvis', className: 'dt-button buttons-collection buttons-colvis btn bg-blue btn-icon dropdown-toggle' } ,
                                    { extend: 'copy', className: 'btn btn-light buttons-copy buttons-html5' },
                                     { extend: 'excel', className: 'btn btn-light buttons-copy buttons-html5' },
                                     { extend: 'csv', className: 'btn btn-light buttons-copy buttons-html5' },
                                     { extend: 'print', className: 'btn btn-light buttons-copy buttons-html5' },
                            ],
						   "select": true,
                           "destroy": true,
                           "processing": true,
                           "serverSide": true,
                           "aaSorting": [],
                           "ajax": "{% url 'photocontest:contest_list' %}",

                           language: {
                                search: "",
                                searchPlaceholder: "Filter"
                            },
							"aoColumnDefs":[
                   				{
								"aTargets": [1], //Columns containing UTC time
								"mRender": function(data, type, full){
									if(data){
										var new_time = moment(data);
										console.log("New Time",new_time.format('MM/DD/YYYY'));
										console.log("New Time",new_time.format('MM/DD/YYYY'));
										new_timezone_time = new_time.format('LL');
										return new_timezone_time;
									}
									return "";
								 }
                   				}

               				 ]

                        });
			return true;
        }

		$("#contestlist thead select").on( 'change', function () {
            table
                .column( $(this).parent().index()+':visible' )
                .search( this.value )
                .draw();
        } );
</script>

    {% if request.user.is_authenticated %}

        {% trans 'Welcome' %} <b>{{ request.user.username }}</b>.

    {% else %}

        {% trans 'You are a guest.' %}

    {% endif %}

    {% include "main/_modal.html" %}

    <div class="card">

        <br>
        <br>
        <div class="card-header header-elements-inline">
            <h5 class="card-title">Contest Template</h5>
        </div>

        <table class="table table-bordered table-hover  datatable-highlight datatable-button-html5-basic" id="contestlist">
            <thead>
                <tr>
                    <th >Contest Name</th>
                    <th >Last Date</th>
                    <th class="no-sort"> Actions </th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>



	</div>

{% endblock %}

source/content/templates/photocontest/participate.html
{% load static %}
{% load widget_tweaks %}
<form method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Participate</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="submit-btn btn btn-primary">Create</button>
  </div>

</form>